<?php
// Generated by tools/business/build_site.py from content.py — do not edit by hand.
// The quiz answers api/lead.php accepts: question key => label, multi, option code => label.
return [
    'pains' => ['label' => 'Muammolar', 'multi' => true, 'options' => ['report' => 'Hisobot oy oxirida yig‘iladi', 'stock' => 'Ombor va dastur mos kelmaydi', 'orders' => 'Buyurtmalar yo‘qoladi', 'person' => 'Hammasi bitta xodimga bog‘liq', 'systems' => 'Tizimlar bir-biri bilan gaplashmaydi', 'money' => 'Pul qayerga ketayotgani ko‘rinmaydi', 'other' => 'Boshqa']],
    'industry' => ['label' => 'Soha', 'multi' => false, 'options' => ['trade' => 'Savdo', 'production' => 'Ishlab chiqarish', 'services' => 'Xizmat ko‘rsatish', 'other' => 'Boshqa']],
    'team' => ['label' => 'Jamoa', 'multi' => false, 'options' => ['upto10' => '10 gacha', 'upto50' => '11–50', 'upto200' => '51–200', 'over200' => '200 dan ko‘p']],
    'systems' => ['label' => 'Tizimlar', 'multi' => true, 'options' => ['excel' => 'Excel yoki Google Sheets', 'onec' => '1C', 'crm' => 'CRM (amoCRM, Bitrix24)', 'site' => 'Sayt yoki internet-do‘kon', 'chat' => 'Telegram va daftar', 'other' => 'Boshqa dastur', 'none' => 'Hech narsa']],
    'timing' => ['label' => 'Muddat', 'multi' => false, 'options' => ['asap' => 'Imkon qadar tez', 'quarter' => '1–3 oy ichida', 'research' => 'Hozircha o‘rganyapman']],
];
